# Generated by Django 5.2.3 on 2025-07-04 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_PREPARO', 'Em preparo'), ('PRONTO', 'Pronto'), ('ENTREGUE', 'Entregue')], default='PENDENTE', max_length=20)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('forma_pagamento', models.CharField(choices=[('PIX', 'PIX'), ('CARTAO', 'Cartão')], max_length=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produto_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_base_pedido', to='produtos.produto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pedidos.pedido')),
            ],
        ),
    ]
